country: china
province: beijing
city: beijing
area: haidian

server:
  port: 80

user:
  name: czt
  age: 22

users:
  - name: zhangsan
    age: 18
  - name: lisi
    age: 19

users2:
  -
    name: zhangsan
    age: 18
  -
    name: lisi
    age: 19

user3: [{name: zhangsan,age: 18},{name: lisi,age: 19}]

#ʹ��${������}��������
app: ${user.name}\t cool

#ʹ��˫���ſ���ʶ��ת���ַ�
app2: "${user.name}\t cool"


# �����࣬���ڷ�װ���������
# ��Spring�������ݵ������У�һ��Ҫ����spring������������
# ʹ��ʱ��Spring��ֱ�ӻ�ȡ��Ϣʹ��

datasource:
  driver: com.mysql.jdbc.Driver
  url: jdbc:mysql://localhost/springboot_db
  username: root
  password: 123456